# Generated by Django 5.0.4 on 2024-08-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('Apellido', models.TextField(max_length=30)),
                ('Nombre', models.TextField(max_length=35)),
                ('Edad', models.IntegerField()),
                ('Fecha_Naci', models.DateField()),
            ],
        ),
    ]
