# Generated by Django 5.0.4 on 2024-08-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='Fecha_Naci',
            new_name='Fecha_Nacimiento',
        ),
    ]
